repos:
  - repo: local
    hooks:
      - id: doctest # required for this pre-commit hook
        name: doctest # required for this pre-commit hook
        types: [python] # required for this pre-commit hook if committing binary files like PDFs
        language: system # required for this pre-commit hook
        entry: python -m doctest

      - id: pylint # required for this pre-commit hook
        name: pylint # required for this pre-commit hook
        entry: pylint # required for this pre-commit hook
        types: [python] # required for this pre-commit hook
        language: system # required for this pre-commit hook

      - id: pyright # required for this pre-commit hook
        name: pyright # required for this pre-commit hook
        entry: pyright # required for this pre-commit hook
        types: [python] # required for this pre-commit hook
        language: system # required for this pre-commit hook

      - id: ruff # required for this pre-commit hook
        name: ruff # required for this pre-commit hook
        types: [python] # required for this pre-commit hook
        language: system # required for this pre-commit hook
        entry: ruff check # required for this pre-commit hook

      - id: ruff-format # required for this pre-commit hook
        types: [python] # required for this pre-commit hook
        language: system # required for this pre-commit hook
        name: ruff-format # required for this pre-commit hook
        entry: ruff format # required for this pre-commit hook

      - id: unittest # required for this pre-commit hook
        name: unittest # required for this pre-commit hook
        language: system # required for this pre-commit hook
        pass_filenames: false # required for this pre-commit hook
        entry: python -m unittest discover -s src/ -p "*.py"
