# https://pre-commit.com/#repository-local-hooks
# A local hook must define id, name, language, entry, and files / types

repos:
  - repo: local
    hooks:
      - id: doctest
        name: doctest
        types: [python]
        language: system
        entry: python -m doctest

      - id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system

      - id: pyright
        name: pyright
        entry: pyright
        types: [python]
        language: system

      - id: ruff
        name: ruff
        types: [python]
        language: system
        entry: ruff check

      - id: ruff-format
        types: [python]
        language: system
        name: ruff
        entry: ruff format

      - id: unittest
        name: unittest
        language: system
        pass_filenames: false # required for this pre-commit hook
        entry: python -m unittest discover -s src/ -p "*.py"
