repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff-format
      - id: ruff # run the linter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [types-all]
        exclude: ^testing/resources/

  - repo: local
    hooks:
      - id: pylint        # required for this pre-commit hook
        name: pylint      # required for this pre-commit hook
        entry: pylint     # required for this pre-commit hook
        types: [python]   # required for this pre-commit hook
        language: system  # required for this pre-commit hook
