on: [push]

name: mypy
jobs:
  strict:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: pip install mypy
      - run: mypy --strict .
