on: [push]

name: pylint
jobs:
  src:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: pip install pylint
      - run: pylint src/
