on: [push]

name: pyright
jobs:
  strict:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: pip install pyright
      - run: pyright
